### ISSUE TITLE
ارور Argument 1 passed to Pishran\Zarinpal\Request::__construct() must be of the type string, null given

### ISSUE THREAD

**Issue by msmsas167** [pishran/Zarinpal#2]
سلام
این ارور موقعی روی هاست تست میکنم میاد
Argument 1 passed to Pishran\Zarinpal\Request::__construct() must be of the type string, null given, called in /home/iranarya/public_html/local/vendor/pishran/zarinpal/src/Zarinpal.php on line 17

**Comment by FaridAghili** [comment]
سلام
مرچنت کدتون رو به تنظیمات اضافه کنید

**.env**
```
...

ZARINPAL_MERCHANT_ID=00000000-0000-0000-0000-000000000000

...
```
