### ISSUE TITLE
ایده ای جهت ایجاد چندین درگاه در یک پکیج

### ISSUE THREAD

**Issue by vahidalvandi** [pishran/Zarinpal#5]
سلام مهندس وقت بخیر
من کد پکیج شما را دیدم پیشنهادی دارم در خصوص اینکه یک پکیج چندین درگاه داشته باشد نمونه های آماده هم وجود داره ولی خیلی مطمین نیستند .
نظرت چیه ؟

**Comment by FaridAghili** [comment]
سلام
ممنون از پیشنهادتون
هدف این پکیج صرفا درگاه زرین‌پال هست

در موردی پیشنهادی که دادید، پکیج زیر به نظر مناسب میاد
https://github.com/shetabit/payment
