### ISSUE TITLE
sandbox حذف کنید

### ISSUE THREAD

**Issue by vahidalvandi** [pishran/Zarinpal#6]
سلام دوست گرامی زرین پال سرویس
sandBox
حذف کرده بهتره در این پکیج هم حذف شود

**Comment by FaridAghili** [comment]
سلام
ممنون که اطلاع دادید

جایی هم در مورد حذف سندباکس اطلاع رسانی کردن؟

**Comment by vahidalvandi** [comment]
اگر تماس بگیرید باهاشون خودشون میگن

**Comment by FaridAghili** [comment]
بله، حق با شماست
ممنون که اطلاع دادید

در نسخه ۴.۲ اصلاح شد
https://github.com/pishran/Zarinpal/releases/tag/v4.2

**Comment by vahidalvandi** [comment]
ممنون از شما یک سوال فنی دستور : Zarinpal که بعد از فانکشن است دقیقا چکار
میکنه و چه تاثیری روی اجرای تابه داره ؟

function zarinpal(): Zarinpal
{
return new Zarinpal();
}

**Comment by FaridAghili** [comment]
اینجا توضیح داده شده

https://www.tutorialspoint.com/php7/php7_returntype_declarations.htm

**Comment by vahidalvandi** [comment]
sepas
