### ISSUE TITLE
مشکل در حالت SandBox

### ISSUE THREAD

**Issue by amirmehr-ir** [pishran/Zarinpal#7]
سلام و وقت بخیر
خسته نباشید

آقا حالت سند باکس رو که تو فایل 
env
با مقدار
ZARINPAL_SANDBOX_ENABLED=true
تعیین میکنم اعمال نمیشه

**Comment by FaridAghili** [comment]
سلام
زرین پال مدتیه که حالت سندباکس رو از APIهاش حذف و غیرفعال کرده، به خاطره همین منم حذفش کردم.
این لینک رو ببینید: 
https://github.com/pishran/Zarinpal/issues/6

**Comment by FaridAghili** [comment]
الان دوباره با پشتیبانی زرین پال تماس گرفتم، تایید کردن که سندباکس غیرفعال شده اما گفتن ممکنه در آینده دوباره برش گردونن.

**Comment by amirmehr-ir** [comment]
من بعد از چند ساعت درگیری با این داستان سندباکس این کلاسی که تو لینک زیر هست رو تست کردم که سندباکس درست کار میکنه 

https://miladworkshop.ir/blog/26-zarinpal-advanced-class.html

**Comment by FaridAghili** [comment]
اگه براتون مقدوره نسخه ۴.۱ رو تست کنید، نسخه قبلی و قبل از حذف سندباکسه:

https://github.com/pishran/Zarinpal/releases/tag/v4.1

اگه اوکیه بفرمایید دوباره اضافه کنم.

**Comment by pyzenberg** [comment]
Zarin Pal is rubbish in every sense of the word. They did this just to force developers to pay and transact in test mode. At the end of the day, this service is really only useful for those betting and criminal sites.
